config/routes.rb
Rails.application.routes.draw do
  get '/pokeyo' => 'pokemons#starter_pokemon'
  get '/users/:id/start' => 'users#startgame'
  get '/users/:id/mudkip' => 'users#mudkip'
  get '/users/:id/treecko' => 'users#treecko'
  get '/users/:id/torchic' => 'users#torchic'
  get '/users/:id/secretbase' => 'users#secretbase'
  get '/users/:id/littleroot' => 'users#littleroot'
  get '/users/:id/r101' => 'users#r101'
  get '/users/:id/r101/capture' => 'users#r101_capture'
  get '/users/:id/r102' => 'users#r102'
  get '/users/:id/petalburg_city' => 'users#petalburg_city'
  get '/users/:id/r103' => 'users#r103'
  get '/users/:id/oldale_town' => 'users#oldale_town'
  get '/users/:id/pokecenter' => 'users#pokecenter'
  get '/users/:id/pokemart' => 'users#pokemart'
  get '/users/:id/pokelotto' => 'users#pokelotto'
  root 'users#index'
  resources :users do
    resources :pokemons
  end
  resources :pokemons

end
#                   DELETE /pokemons/:id(.:format)                     pokemons#destroy

app/models/pokemon.rb
class Pokemon
  include Mongoid::Document
  field :name
  field :level
  field :nickname
  field :wild
  field :species
  field :description
  field :types
  field :sex
  field :moves
  field :img_url
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name
  field :money, default: 3000
  field :location, default: "littleroot"
  has_many :pokemons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]
  def index
    @pokemons = Pokemon.all
  end
  def show
  end
  def new
  end
  def create
  end
  def edit
  end
  def update
    if @pokemon.update(pokemon_params)
      redirect_to @pokemon
    end
  end
  def destroy
    @pokemon.destroy
    redirect_to '/users/'+@pokemon.user.id
  end
  def starter_pokemon
    uri = "http://pokeapi.co/api/v2/pokemon/mudkip"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["name"]
    puts '-----------------------------------'
  end
  private
  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end
  def pokemon_params
    params.require(:pokemon).permit(:name, :nickname, :wild, :species, :type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :startgame, :mudkip, :treecko, :torchic, :secretbase, :littleroot, :r101, :r101_capture, :oldale_town, :r103, :r102, :petalburg_city]
  def index
    @users = User.all.to_a
    puts @users
  end
  def show
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, success: "Successfully made"
    else
      puts "error"
      redirect_to '/users/new', notice: "Invalid form input. No input fields can be left blank"
    end
  end
  def edit
  end
  def update
  end
  def destroy
    @user.destroy
    redirect_to '/users'
  end
  #startgame is where one starts his or her journey as a pokemon trainer!(choose your starter page)
  def startgame
    @user.money = 3000
    @user.save
    puts 'testing if this works'
    uri = "http://pokeapi.co/api/v2/pokemon/mudkip"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["sprites"]["front_default"]
    puts '-----------------------------------'
    mudkipz = response
    @mudkip = mudkipz
    uri = "http://pokeapi.co/api/v2/pokemon/torchic"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["sprites"]["front_default"]
    puts '-----------------------------------'
    torchicz = response
    @torchic = torchicz
    uri = "http://pokeapi.co/api/v2/pokemon/treecko"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["sprites"]["front_default"]
    puts '-----------------------------------'
    treeckoz = response
    @treecko = treeckoz
  end
  def mudkip
    puts '-------------'
    puts @user.name
    puts 'mudkip'
    puts '-------------'
    uri = "http://pokeapi.co/api/v2/pokemon/mudkip"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["sprites"]["front_default"]
    puts '-----------------------------------'
    @user.pokemons.delete_all
    @user.pokemons.create(name: "Mudkip", wild: false, level: 5, species: "mudkip", description: "The fin on MUDKIP’s head acts as highly sensitive radar. Using this fin to sense movements of water and air, this POKéMON can determine what is taking place around it without using its eyes.", types: response["types"][0]["type"]["name"], sex: "m", moves: ["Growl", "Tackle"], img_url: response['sprites']['front_default'])
    @user["money"] = @user["money"] * 2
    @user.save
    puts @user.money
  end
  def treecko
    puts @user.name
    puts 'treecko'
    puts '-------------'
    uri = "http://pokeapi.co/api/v2/pokemon/treecko"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["sprites"]["front_default"]
    puts '-----------------------------------'
    @user.pokemons.delete_all
    @user.pokemons.create(name: "Treecko", wild: false, level: 5, species: "treecko", description: "TREECKO has small hooks on the bottom of its feet that enable it to scale vertical walls. This POKéMON attacks by slamming foes with its thick tail.", types: response["types"][0]["type"]["name"], sex: "m", moves: ["Leer","Pound"], img_url: response['sprites']['front_default'])
  end
  def torchic
    puts @user.name
    puts 'torchic'
    puts '-------------'
    uri = "http://pokeapi.co/api/v2/pokemon/torchic"
    response = HTTParty.get(uri)
    puts '-----------------------------------'
    puts response["sprites"]["front_default"]
    puts '-----------------------------------'
    @user.pokemons.delete_all
    @user.pokemons.create(name: "Torchic", wild: false, level: 5, species: "torchic", description: "TORCHIC sticks with its TRAINER, following behind with unsteady steps. This POKéMON breathes fire of over 1,800 degrees F, including fireballs that leave the foe scorched black.", types: response["types"][0]["type"]["name"], sex: "m", moves: ["Growl", "Scratch"], img_url: response['sprites']['front_default'])
    @user["money"] = @user["money"]/2
    @user.save
    puts @user.money
  end
  def secretbase
  end
  def littleroot
    @user.location = "littleroot"
    @user.save
  end
  def r101
    @user.location = "r101"
    @user.save
  end
  def r101_capture
    rannum = rand(1..100)
    puts rannum
    if rannum.between?(1,45)
      encounter = "zigzagoon"
    elsif rannum.between?(46,90)
      encounter = "wurmple"
    elsif rannum.between?(91,100)
      encounter = "poochyana"
    end
    puts encounter
    uri = "http://pokeapi.co/api/v2/pokemon/"+encounter
    response = HTTParty.get(uri)
    puts response["name"]
    @user.pokemons.create(name: response["name"], wild: false, level: 2, species: response["species"], types: response["types"][0]["type"]["name"], sex: 'm')
    @first_random = response
  end
  def oldale_town
    @user.location = "oldale_town"
    @user.save
  end
  def r103
    @user.location = "r103"
    @user.save
  end
  def r102
    @user.location = "r102"
    @user.save
  end
  def petalburg_city
    @user.location = "petalburg_city"
    @user.save
  end
  def r104
  end
  def rustboro_city
  end
  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :money)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokemonRubyOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemons/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<%= form_for Pokemon.find(@pokemon.id), :method => :PUT do |f| %>
  <%= f.label :nickname, 'Nickname:', class: 'description'%>
  <%= f.text_field :nickname, :value => @pokemon.nickname %>
  <%= f.submit "Confirm edit" %>
<% end %>
</body>
</html>

app/views/pokemons/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

</body>
</html>

app/views/pokemons/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

</body>
</html>

app/views/pokemons/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<img src="<%=@pokemon.img_url%>">
<p>This is <%=@pokemon.nickname%>, and he is a <%=@pokemon.name%>!</p>
Level: <%=@pokemon.level%>
<br>
Pokedex Entry: <%=@pokemon.description%>
<br>
Trainer: <a href="/users/<%=@pokemon.user.id%>"><%=@pokemon.user.name%></a>
<br>
 <a href='/users/<%=@pokemon.user.id%>/<%=@pokemon.user.location%>'>Back to game</a>
 <br>
<%= button_to "Release", pokemon_path(:id => @pokemon.id), :method => :delete %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name, 'Name:', class: 'description'%>
  <%=f.text_field :name%>
  <br>
  <%= radio_button_tag(:sex, "boy") %>
  <%= label_tag(:sex_boy, "I am a boy") %>
  <%= radio_button_tag(:sex, "girl") %>
  <%= label_tag(:sex_girl, "I am a girl") %>
  <br>
  <%=f.submit%>
<%end%>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Pokemon Ruby (on Rails)</h1>
<%@users.each do |user|%>
<a href='/users/<%=user.id%>'>Continue as <%=user.name%></a>
<%end%>
<br>
<a href="/users/new">New Game</a>
</body>
</html>

app/views/users/mudkip.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<p>Give it a nickname?</p>
<%= form_for Pokemon.find(@user.pokemons[0].id), :method => :PUT do |f| %>
  <%= f.label :nickname, 'Nickname:', class: 'description'%>
  <%= f.text_field :nickname, :value => @user.pokemons[0].name %>
  <%= f.submit "Confirm edit" %>
<% end %>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h2>Are you a boy or a girl?</h2>
<%= render :partial => 'form' %>
</body>
</html>

app/views/users/pokecenter.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Welcome to the Pokemon Center!</h1>
</body>
</html>

app/views/users/pokelotto.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Welcome to the Pokemon Lottery!</h1>
</body>
</html>

app/views/users/r101.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Route 101</h1>
<h2>A route in southwestern Hoenn, connecting Littleroot Town and Oldale Town.</h2>
<h3>This place is kind of dangerous but you have Pokemon to help fight off the wild Pokemon so it's ok.</h3>
Options:
<ul>
  <li><a href="/users/<%=@user.id%>/littleroot">Go back to Littleroot Town</a></li>
  <li><a href="/users/<%=@user.id%>/oldale_town">Go to Oldale Town</a></li>
  <li><a href="/users/<%=@user.id%>/secretbase">Go to the Secret Base</a></li>
  <li><a href="/users/<%=@user.id%>/r101/capture">Catch Pokemon</a></li>
</ul>
</body>
</html>

app/views/users/r101_capture.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<img src="<%=@first_random["sprites"]["front_default"]%>">
<br>
You caught <%=@first_random["name"]%>! Congratulations!
<br>
<a href="/users/<%=@user.id%>/r101">Go Back</a>
</body>
</html>

app/views/users/r102.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Route 102</h1>
<h2>A route in western Hoenn, connecting Oldale Town and Petalburg City.</h2>
<h3>This place is kind of dangerous but you have Pokemon to help fight off the wild Pokemon so it's ok.</h3>
Options:
<ul>
  <li><a href="/users/<%=@user.id%>/oldale_town">Go back to Oldale Town</a></li>
  <li><a href="/users/<%=@user.id%>/petalburg_city">Go to Petalburg City</a></li>
  <li><a href="/users/<%=@user.id%>/secretbase">Go to the Secret Base</a></li>
  <li><a href="/users/<%=@user.id%>/r102/capture">Catch Pokemon</a></li>
</ul>
</body>
</html>

app/views/users/r103.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Route 103</h1>
<h2>A route in southwestern Hoenn, connecting Littleroot Town and Oldale Town.</h2>
<h3>Due to the route's location, it has become a popular training spot for Trainers.</h3>
Options:
<ul>
  <li><a href="/users/<%=@user.id%>/littleroot">Go to Littleroot Town</a></li>
  <li><a href="/users/<%=@user.id%>/oldale_town">Go back to Oldale Town</a></li>
  <li><a href="/users/<%=@user.id%>/secretbase">Go to the Secret Base</a></li>
  <li><a href="/users/<%=@user.id%>/r103/capture">Catch Pokemon</a></li>
</ul>
</body>
</html>

app/views/users/secretbase.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Secret Base</h1>
<h2>This is your Secret Base <%=@user.name%>!</h2>
Money: <%=@user.money%>
<ul>
  <li><a href="/users/<%=@user.id%>/pokecenter">Pokemon Center</a></li>
  <li><a href="/users/<%=@user.id%>/pokemart">PokeMart</a></li>
  <li><a href="/users/<%=@user.id%>/pokelotto">PokeLotto</a></li>
  <li><a href="/users/<%=@user.id%>/">View Team</a></li>
</ul>
<a href="/users/<%=@user.id%>/<%=@user.location%>">Continue your adventure</a>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<%if @user.pokemons.length === 0%>
  <a href="/users/<%=@user.id%>/start">Start your Pokemon adventure!</a>
<%else%>
  <p><%=@user.name%>'s team:</p>
  <%@user.pokemons.each do |pokemon|%>
    <a href='/pokemons/<%=pokemon.id%>'><%=pokemon.name%></a>
  <%end%>
  <br>
  <a href='/users/<%=@user.id%>/<%=@user.location%>'>Back to game</a>
  <br>
  <a href="/users">Back Save File Selection</a>
<%end%>
<br>
<%= button_to "Delete Save File", user_path(:id => @user.id), :method => :delete %>
</body>
</html>

app/views/users/startgame.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h2>Choose your starter!</h2>
<a href="/users/<%=@user.id%>/treecko"><img src="<%=@treecko['sprites']['front_default']%>"></a>
<br>
Name: <%=@treecko["name"]%>
<br>
Type(s): <%=@treecko["types"][0]["type"]["name"]%>
<br>
<a href="/users/<%=@user.id%>/torchic"><img src="<%=@torchic['sprites']['front_default']%>"></a>
<br>
Name: <%=@torchic["name"]%>
<br>
Type(s): <%=@torchic["types"][0]["type"]["name"]%>
<br>
<a href="/users/<%=@user.id%>/mudkip"><img src="<%=@mudkip['sprites']['front_default']%>"></a>
<br>
Name: <%=@mudkip["name"]%>
<br>
Type(s): <%=@mudkip["types"][0]["type"]["name"]%>
</body>
</html>

app/views/users/torchic.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<p>Give it a nickname?</p>
<%= form_for Pokemon.find(@user.pokemons[0].id), :method => :PUT do |f| %>
  <%= f.label :nickname, 'Nickname:', class: 'description'%>
  <%= f.text_field :nickname, :value => @user.pokemons[0].name %>
  <%= f.submit "Confirm edit" %>
<% end %>
</body>
</html>